apiVersion: v1
kind: Pod
metadata:
    name: webapp
    labels:
      app: nginx
spec:
  containers:
  - name: boxone
    image: docker.io/library/nginx:latest
    ports:
    - containerPort: 80
  - name: boxtwo
    image: docker.io/library/redis:latest
