apiVersion: v1
kind: Pod
metadata:
  name: prdapache
  labels:
    name: mysql
    managed-by: IT
    version: "2.4"
    component: frontend
    part-of: employee
    instance: jan2025
    client: abc
    env: prod
spec:
  containers:
  - name: boxone
    image: nginx
    volumeMounts:
      - name: configfile
        mountPath: /etc/nginx/conf.d/
      - name: webfile
        mountPath: /usr/share/nginx/html/
  volumes: 
    - name: configfile
      configMap:
        name: webconfig
    - name: webfile
      configMap:
        name: webdata
