apiVersion: v1
kind: Pod
metadata:
  name: dba
  labels:
    name: mysql
    managed-by: IT
    version: "2.4"
    component: frontend
    part-of: employee
    instance: jan2025
    client: abc
    env: prod
spec:
  containers:
  - image: docker.io/library/mysql
    name: boxone
    ports:
    - containerPort: 3306
    env:
    - name: MYSQL_ROOT_PASSWORD
      #value: "school1"
      valueFrom:
        secretKeyRef:
          name: sqlcreds
          key: passsword
