apiVersion: v1
kind: Pod
metadata:
  name: emp-front
  namespace: dev
  labels:
    name: nginx
    managed-by: IT
    version: "2.4"
    component: frontend
    part-of: employee
    instance: jan2025
    client: abc
    env: prod
spec:
  containers:
  - image: nginx
    name: nginx
    ports:
    - containerPort: 80
