apiVersion: v1
kind: Pod
metadata:
  name: guarantee-app
  labels: 
    name: apache
    version: "3.4"
    managed-by: devops
    instance: jan2023
    component: frontend
    part-of: employee
spec:
  containers:
  - name: boxone
    image: docker.io/lovelearnlinux/webserver:v1
    ports:
    - containerPort: 80
    resources:
      limits:
        cpu: 100m
        memory: 128Mi
      requests: 
        cpu: 100m
        memory: 128Mi

